### ISSUE TITLE
Aluno PedidoAula

### ISSUE THREAD

**Issue by Muciojaziel** [Muciojaziel/tocomduvidas#14]
Estórias do Usuário:
**Como ALUNO quero realizar um PEDIDOAULA informando o assunto, área, preço, horário e data que se ajusta a minha DISPONIBILIDADE**

Testes de aceitação:
- Deve ser possível o aluno lançar no site informações acerca do  assunto, área, preço, melhor horário e data que gostaria de obter o serviço.

**Comment by gcsgivanildo** [comment]
@Muciojaziel está com o status feito, mas se não foi feito, eu posso fazer, coloca o status para em andamento

**Comment by Muciojaziel** [comment]
@gcsgivanildo ok! alterado! Pode fazer, e vou assiná-la pra vc!

**Comment by gcsgivanildo** [comment]
@Muciojaziel pode fechar essa issue #14
