### ISSUE TITLE
Cadastro Aluno

### ISSUE THREAD

**Issue by Muciojaziel** [Muciojaziel/tocomduvidas#2]
Estórias do usuário: **Como ALUNO desejo ME CADASTRAR para USAR O SERVIÇO [5]**

Testes de Aceitação:
- O aluno deve fornecer informações como Nome, email, senha. ~~nome Usual, CPF, Data de Nascimento, Endereço, telefone, email, formação~~
- No cadastro, é preciso usuário assinalar perfil: aluno ou professor
~~-O aluno deve informar a área de interesse, para que desta forma, outros alunos ou professores possam recomendar e indicar professores~~

**Comment by gcsgivanildo** [comment]
@Muciojaziel pode fechar essa issue
