### ISSUE TITLE
Professor Upload

### ISSUE THREAD

**Issue by Muciojaziel** [Muciojaziel/tocomduvidas#20]
Estória do usuário:
**Como PROFESSOR desejo inserir material de aulas**

Testes de aceitação:
- Deve ser possível o professor fazer upload de arquivos de seu interesse: audio, video, pdf, pptx etc.

**Comment by lsoaresesilva** [comment]
Como está essa atividade?

**Comment by Muciojaziel** [comment]
Falta melhorar a interface de usuário, e verificar o por que há substituição do arquivo quando faço upload de 2 ou mais arquivos de qualquer tipo.

**Comment by Muciojaziel** [comment]
#24
