### ISSUE TITLE
Cadastro Professor

### ISSUE THREAD

**Issue by Muciojaziel** [Muciojaziel/tocomduvidas#4]
Estória do usuário: **Como PROFESSOR desejo ME CADASTRAR para RECEBER NOTIFICAÇÕES de PEDIDOSAULA**

Testes de Aceitação:
- Deve ser informado no cadastro: 
-> FORMAÇÃO, ESPECIALIDADE, ÁREA DE CONHECIMENTO, ÁREA DE ATUAÇÃO.
-> EXPERIÊNCIA PROFISSIONAL
-> EVENTOS QUE PARTICIPOU COMO OUVINTE ou PALESTRANTE

**AREA DE CONHECIMENTO** deve ser detalhada:
- Ex: PORTUGUÊS, GEOGRAFIA, COMPUTAÇÃO.

**AREA DE ATUAÇÃO** deve ser detalhada:
- Ex: GRAMÁTICA, ROCHAS, REDES, BD, PROGRAMAÇÃO JAVA

**Comment by gcsgivanildo** [comment]
@Muciojaziel  pode fechar
