### ISSUE TITLE
PedidoAula

### ISSUE THREAD

**Issue by Muciojaziel** [Muciojaziel/tocomduvidas#5]
Estória do usuário: **Como ALUNO desejo realizar PEDIDOAULA**

Testes de aceitação:
- Deve ser possível ESCOLHER o assunto, área, preço, horário e data do PEDIDOAULA.

**Comment by Muciojaziel** [comment]
[trazido do trello] Além do mais poderíamos fazer com que o professor no cadastro informe um PRÉ-HORÁRIO DE DISPONIBILIDADE. Nada obrigatório a cumprir mas que a gente possa pegar esse pré-horário e mostrar ao aluno pra que quando ele faça o anúncio, tenha algum retorno imediato.

Esse 2 ponto, acho que o aluno ao fazer um anuncio deve ter algum retorno da plataforma, esse então poderia ser um "mapa" com os professores disponíveis... No UBER o cara traça a rota e tem lá mostrando os motoristas e o preço[, poderiam me ajudar nesse quesito? Como a gente poderia melhorar essa ideia? É viável?
@gcsgivanildo @Edjaniorodrigues

**Comment by lsoaresesilva** [comment]
@Muciojaziel altera o título para: Anúncio de aula.

Em seguida, coloca na descrição:

Estória do usuário: Como ALUNO desejo ANUNCIAR UMA AULA
Prioridade: 5

Testes de aceitação:

* Deve ser possível ESCOLHER o horário, dia da aula anunciada
* O aluno deve, depois do anúncio, visualizar um TIPO DE MAPA de professores disponíveis para o horário anunciado [ não sei se isso cabe]

**Comment by Muciojaziel** [comment]
Ok!
