### ISSUE TITLE
Professor recebe Notificações

### ISSUE THREAD

**Issue by Muciojaziel** [Muciojaziel/tocomduvidas#9]
Estórias do usuário:
**Como PROFESSOR desejo RECEBER NOTIFICAÇÕES DE ANÚNCIOS**

Testes de Aceitação:
- Deve ser possível o professor receber notificações do anúncios referentes a sua disciplina

**Comment by Muciojaziel** [comment]
Os anúncios estão chegando sem restrições, todo professor receber todos anúncios. @gcsgivanildo era isso que iria te falar e esqueci. Vamos corrigir?

**Comment by gcsgivanildo** [comment]
Assina essa Issue #9 para mim, e coloca em andamento

**Comment by gcsgivanildo** [comment]
@Muciojaziel Assina essa Issue #9 para mim, e coloca em andamento

**Comment by Muciojaziel** [comment]
@gcsgivanildo atenta que a parte de notificação está pronta o professor ta recebendo a mesma!

**Comment by Muciojaziel** [comment]
#27

**Comment by Muciojaziel** [comment]
@gcsgivanildo houve poucas mudanças, mas a issue atualizada é essa #27 .  Estou fechando essa.
